# Generated by Django 5.2.17 on 2026-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('USER_UPDATE', 'User Update'), ('USER_DELETE', 'User Delete'), ('CARD_VIEW', 'Card View'), ('CARD_STATUS_UPDATE', 'Card Status Update'), ('CREDIT_LIMIT_UPDATE', 'Credit Limit Update'), ('TRANSACTION_VIEW', 'Transaction View'), ('CSV_EXPORT', 'CSV Export'), ('DASHBOARD_VIEW', 'Dashboard View'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
